kind: pipeline
name: feeds

steps:
- name: build
  image: golang:1.13
  commands:
    - go test ./...
    - go install
  when:
    event:
    - push

- name: build_serverless
  image: golang:1.13.0-alpine
  environment:
    LAMBDA_BUILD: on
    PORT: 8888
  commands:
  - go build -o main main.go
  - apk add zip
  - zip -r -9 lambda-feeds.zip main
  - apk add tzdata
  - cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" >  /etc/timezone
  when:
    event:
    - promote

- name: s3-publish
  image: plugins/s3
  settings:
    acl: private
    region: ap-southeast-1
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    bucket: lbd-project
    target: project-feed
    source: lambda-feeds.zip
  when:
    event:
    - promote

- name: deploy_serverless
  image: scnace/drone-lambda-plugin
  settings:
    function_name: feeds
    s3_bucket: lbd-project
    aws_secret_access_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    aws_access_key_id:
      from_secret: AWS_ACCESS_KEY_ID
    file_name: project-feed/lambda-feeds.zip
    region: ap-southeast-1
  when:
    event:
    - promote

- name: publish_dockerhub
  image: plugins/docker
  settings:
    repo: scnace/feeds
    auto_tag: true
    username:
        from_secret: DOCKERHUB_USER
    password:
        from_secret: DOCKERHUB_PASSWORD
    dockerfile: Dockerfile
  when:
    event:
    - push
    branch:
    - master
