kind: pipeline
name: feeds

steps:
- name: build
  image: golang:1.13
  environment:
    LAMBDA_BUILD: on
    PORT: 8888
  commands:
  - go build -o main main.go
  - zip -r -9 lambda-feeds-${DRONE_BUILD_NUMBER}.zip main

- name: s3-publish
  image: plugins/s3
  acl: private
  region: ap-southeast-1
  secret_key:
    from_secret: AWS_SECRET_ACCESS_KEY
  access_key:
    from_secret: AWS_ACCESS_KEY_ID
  bucket: lbd-project
  target: project-feed
  source: lambda-project-${DRONE_BUILD_NUMBER}.zip
  when:
    event:
    - push
    branch:
    - master
    - dev

- name: deploy_serverless
  image: omerxx/drone-lambda-plugin
  pull: true
  function_name: feeds
  s3_bucket: lbd-project
  aws_secret_access_key:
    from_secret: AWS_SECRET_ACCESS_KEY
  aws_access_key_id:
    from_secret: AWS_ACCESS_KEY_ID
  filename: project-feed/lambda-project-${DRONE_BUILD_NUMBER}.zip
  when:
    event:
    - push
    branch:
    - master
    - dev

- name: publish_dockerhub
  image: plugins/docker
  settings:
    repo: scnace/feeds
    autotag: true
    username:
        from_secret: DOCKERHUB_USER
    password:
        from_secret: DOCKERHUB_PASSWORD
    dockerfile: Dockerfile
  when:
    event:
    - push
    branch:
    - master
